### ISSUE TITLE
Simulator building

### ISSUE THREAD

**Issue by patrickjohncyh** [m8pple/arch2-2018-cw#10]
1. When building the simulator with "make simulator" as in the spec, is the makefile based on the one provided at [LangProc/arch2-2017-cw-dt10](https://github.com/LangProc/arch2-2017-cw-dt10) or will it be another makefile where the compilation would be inclusive of all c++ files in the src folder?

2. Is the use of c++11 allowed?

**Comment by m8pple** [comment]
The makefile is supplied as part of your submission, so it can be whatever you want. It can be based
on the example given, or completely different. The idea is to give you complete control over the
build process, and how you want to organise and build your files.

So yes, c++11 is fine (or even c++14, as I think that is supported in g++ in the labs) - you just
need to add that flag to your makefile.
