### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by gioannides** [m8pple/arch2-2018-cw#11]
When executing a branch instruction, is it needed to simulate delayed branches as well? Meaning having to execute the next instruction in instruction memory, prior to taking the branch.

**Comment by m8pple** [comment]
Yes, that is required, as it is part of the MIPS ISA spec - this is one case where they let the
micro-architectural concerns bubble their way up to be a formal part of the ISA. All MIPS-1
compilers will produce code that assumes a delay slot, so you're trying to be compatible
with them. With the benefit of hindsight and silicon scaling that decision was probably
wrong (for example the recent [RISC-V ISA](https://en.wikipedia.org/wiki/RISC-V) deliberately
omitted them), but at the time it was probably right.

Supporting the delay slot is actually very easy, as long as you have thought about the
flow of your simulator, and separated the generic parts (e.g. advancing the PC) from the
per-instruction behaviour.

I think the description of PC behaviour [given here](http://www.mrc.uidaho.edu/mrc/people/jff/digital/MIPSir.html) is
quite clean.
