### ISSUE TITLE
Format of .bin

### ISSUE THREAD

**Issue by kyczawon** [m8pple/arch2-2018-cw#12]
What is the format of the binary inputted into our simulator? Is each instruction made of 32 bits, 8 hex digits, or two blocks of 4 hex digits separated by a space (same as the .bin created by the makefile)?

**Comment by m8pple** [comment]
If the example makefile is creating a hexadecimal file, then there is probably an error in
the makefile - it should be creating a direct binary dump, so it's possible the wrong flag
ended up being passed to objdump. I'll look into it later.

So the binary should literally contain binary, as described in the spec - each
instruction is 4 bytes, so a one instruction binary file would be 4 bytes long.

**Comment by edpickup** [comment]
For further clarification, would the following be the correct form for some arbitrary binary

11110000111100001111000011110000
11001100110011001100110011001100
00010001000100010001000100010001

Ignoring what those instructions actually are, is this the correct format for the binary?

**Comment by m8pple** [comment]
Sorry, didn't notice this extra response when I swept the issues last time.

It's not really clear what you mean - if you mean would a text-file containing:
```
11110000111100001111000011110000
11001100110011001100110011001100
00010001000100010001000100010001
```
be correct, then no it wouldn't. The size of the file would
be 99 bytes or something similar.

If you mean could it be a binary file containing those bits,
then yes, but the size of that file would be exactly 12 bytes.
