### ISSUE TITLE
MFLO/MFHI Undefined behaviours

### ISSUE THREAD

**Issue by VasiliosRallis** [m8pple/arch2-2018-cw#15]
In the PDF that you recommended (i.e. http://math-atlas.sourceforge.net/devel/assembly/mips-iv.pdf)

It says if we read the HI or LO registers when the next 2 instructions write to them, the result from the read will be undefined.

I'm assuming this has something to do with the way pipelining works. Do we need to implement this?

**Comment by m8pple** [comment]
Yes, it is mainly related to pipelining.

The wonderful thing about `undefined` is that it allows you to do whatever is architecturally
convenient for you. So you are perfectly untitled to just return the `correct` result, as that
probably makes life easier for you.

Trying to track those constrains makes much more work for you, and then there is no correct
way for a tester to actually test the results - even if it creates instructions that violate this
condition, it has no idea what a correct implementation should do in response (as a correct
implementation could do nothing).
