### ISSUE TITLE
IO technicalities

### ISSUE THREAD

**Issue by ghost** [m8pple/arch2-2018-cw#17]
In terms of IO interfacing, should IO be accessed if the accessed address is for example 0x30000001 or is it strictly at 0x30000000

**Comment by m8pple** [comment]
I think this is related to #14?

That should still be strengthened in the spec - I welcome potential rewording or clarification of the spec...

**Comment by ghost** [comment]
my bad!

**Comment by m8pple** [comment]
No problem - it's a good question to ask.
