### ISSUE TITLE
INTERNAL, STACK, FUNCTION

### ISSUE THREAD

**Issue by gioannides** [m8pple/arch2-2018-cw#18]
INTERNAL
STACK
FUNCTION

These are not part of the ISA. However in the specification these are included after the instructions. What are we required to do with them?

**Comment by gioannides** [comment]
More specifically on INTERNAL

**Comment by m8pple** [comment]
You aren't required to do anything with them, it was more because people might
ask what to put in if they are doing integration tests (i.e. tests that aren't trying
to look for a specific instruction, but are trying to test a broad combination of
instructions).

I'll clarify the wording - thanks.
