### ISSUE TITLE
MAKEFILE

### ISSUE THREAD

**Issue by gioannides** [m8pple/arch2-2018-cw#19]
The following lines in the MAKEFILE prevent the assembler from compiling any section other than the .text. Therefore when compiling C files,  a .data segment is not initialized. Is the specification required to be so? Or can we change this to compile all sections, so C programs can be tested more completely?

%.mips.bin : %.mips.elf
$(MIPS_OBJCOPY) -O binary **--only-section=.text** $< $@

**Comment by m8pple** [comment]
To be clear, this is only about _extracting_ sections, not compiling them.
But you are correct - as it stands, only the `.text` segment is extracted,
so we only get the code.

You can change your makefile to extract different the data section too, but
there is then a problem with a general data section, as we currently don't have
any mechanism for loading initialised data. However, zero initialised data
should work fine, as it should be located by the linker in our mutable
RAM section by the linker.

So enumerating the possible sections, and where we could put them,
we have:
- `.text` : Executable code, goes to instruction ROM
- `.rodata` : Read-only data. Can be placed into ROM, even though it isn't code.
- `.bss` : uninitialised mutable data. Can go in RAM.
- `.data` : Initialised mutable data. No way to actually support this.

Here you're pushing against the limitations of our relatively simple
simulator interface (in a good way). We could have define the interface
to be more complex, and supported loading different sections, but
it means the spec would need to be longer and adds additional points
of failure.

So one option is to only use `.rodata` and `.bss` sections, which means
using only `const` globals (possibly with `-fno-common`) or zero-initialised
variables). Another option is to add a private extension command which
allows you to load a data segment - this allows you to test your own
simulator on more advanced code, but won't work for other peoples.

**Comment by gioannides** [comment]
Thank you
