### ISSUE TITLE
Memory locations

### ISSUE THREAD

**Issue by dangerbot3pic** [m8pple/arch2-2018-cw#20]
When accessing memory, will the binary know the addresses of the start point of each part of RAM ie. will it know that read/write memory begins at 0x..... (whatever address it is) or will it begin from 0 and we have to provide the offset to map it to its actual location in memory? Also, if the latter case, how will the binary be able to write to address 0 for program termination and how will it access the get_c and put_c locations?

**Comment by m8pple** [comment]
It's the first one, so the binary knows the positions of all parts of the address map,
so it can directly refer to the start of RAM as it knows the exact address.

For example, look at the disassembly for `SW-putc.mips.s` from the formative tests.

Note that the binary doesn't write to address 0, it executes the "instruction"
at address 0.
