### ISSUE TITLE
Is it plagiarism?

### ISSUE THREAD

**Issue by VasiliosRallis** [m8pple/arch2-2018-cw#22]
Could we copy random C code off the internet and use it as a test or would this be considered to be plagiarism.

**Comment by m8pple** [comment]
As long as you attribute it very clearly (e.g. by annotating the input source code with
the author, source, and any license) and there is a good reason, then it is fine.

However, I would only really expect this as an integration or soak test - so if it is less
about testing individual instructions (which is more to do with the assessment),
and more about convincing yourself that it is a fully functioning MIPS CPU. 
Hopefully your CPU should be able to run pretty much anything that doesn't
make use of co-processor/system instructions, up to and including the output
of your compilers from next term. So if you want to add extra stress tests using
test-cases from other sources, then go for it - it isn't strictly necessary for the
the assessment, but is a very good thing to do for it's own sake (and makes it

Note that if the C code is something like GPL, then you would need to put
your project under GPL. That doesn't mean you have to give it away or publically
release it, but it should technically be given a GPL license file.
