### ISSUE TITLE
Shifting right g++

### ISSUE THREAD

**Issue by gioannides** [m8pple/arch2-2018-cw#23]
The result of E1 >> E2 is E1 right-shifted E2 bit positions. If E1 has an unsigned type or if E1 has a signed type and a nonnegative value, the value of the result is the integral part of the quotient of E1 / 2^E2. **If E1 has a signed type and a negative value, the resulting value is implementation defined and can be either an arithmetic (signed) shift or a logical (unsigned) shift**. **Right shifting of negative quantities** is **implementation defined**. Since g++ produces negative result when shifting a signed number, can it be safely assumed that this will be the case during assessing?

**Comment by m8pple** [comment]
Interesting - so we're coming up against potential differences between language semantics,
and ISA semantics. So just for teaching purposes, C has three main ways of resolving
corner-cases, ambiguous constructs, and incorrect code:
- Implementation defined : the particular C compiler must state how it resolves the ambiguity,
   and must stick to it.
- Unspecified behaviour : there are a limited set of correct interpretations of the ambiguity, and
   the C compiler must pick one of them (in whatever way is convenient).
- Undefined behaviour : the programmer has done something wrong, and the compiler is
   able to resolve it in any way at all, including optimising away the whole program, crashing,
   providing random behaviour (gives a different result each time the program runs), or giving
   the "correct" (i.e. the programmer expected) behaviour.

Undefined behaviour is the dangerous one, and most commonly seen in the warning:

> warning : 'return' with no value, in function returning non-void.

which many students ignore (at their peril!)

To return to your specific question, as you say, it is _implementation_ defined, so the
relevant documentation [for gcc is here](https://gcc.gnu.org/onlinedocs/gcc/Integers-implementation.html#Integers-implementation), which says:

> _The results of some bitwise operations on signed integers (C90 6.3, C99 and C11 6.5)._
> Bitwise operators act on the representation of the value including both the sign and value bits, where the sign bit is considered immediately above the highest-value value bit. Signed ‘>>’ acts on negative numbers by sign extension.
> 
> As an extension to the C language, GCC does not use the latitude given in C99 and C11 only to treat certain aspects of signed ‘<<’ as undefined. However, -fsanitize=shift (and -fsanitize=undefined) will diagnose such cases. They are also diagnosed where constant expressions are required.
> 

We know that we are using g++ (which is derived from gcc, and inherits the same
implementation defined behaviour), so:

Yes - you can safely assume that.

**Comment by gioannides** [comment]
Okay, Thank you.
