### ISSUE TITLE
GETC

### ISSUE THREAD

**Issue by HarryAnkers** [m8pple/arch2-2018-cw#30]
If you enter multiple characters for getc or even press a character and hit return is each consecutive call of get suppose to call the next character in the previous cin or flush the stream?

**Comment by m8pple** [comment]
Each load from GETC should return the next character, just like consecutive
calls to `getchar` would return a new character.

So if you had a file called `wibble.txt` which contained:
```
hello
```
and a binary `dump.bin` that contained something like:
```
mv $3, ADDR_GETC
mv $4, -1
top:
lw $8, $3(0)
addi $2, $2, 1
bne $2, $4, top
nop
```
then you ran the simulator using:
```
cat wibble.txt | bin/mips_simulator dump.bin
```
You would expect the loop to execute 6 times. The first
five times it would get `h`, then `e`, then `l`, and so on, and
on the sixth it would get -1 and exit.
