### ISSUE TITLE
Is python installed on the test machines?

### ISSUE THREAD

**Issue by ES5017** [m8pple/arch2-2018-cw#33]
Can I create my testbench in python? If so, which version?

**Comment by jjd06** [comment]
Yes you can. Any version you like, but you should expect none to be installed by default. As per the [spec](https://github.com/m8pple/arch2-2018-cw), your testbench *can* be set up by calling `make testbench` and *must* be executable by calling `bin/mips_testbench`.

**Comment by szymonkobus** [comment]
You might find [this](https://docs.python-guide.org/shipping/freezing/) article about **python freezing** useful.
