### ISSUE TITLE
Test environment versions

### ISSUE THREAD

**Issue by lhl2617** [m8pple/arch2-2018-cw#36]
What are the versions of the following (and other relevant) tools/dependencies in the test environment?

- Linux Kernel
- Ubuntu Release
- g++
- mips-linux-gnu-gcc

It would be helpful if we could obtain the output from:
```
uname -a 
g++ --version
mips-linux-gnu-gcc --version
```

**Comment by jjd06** [comment]
The environment is as follows.

Ubuntu 16.04.1 x86_64
Kernel build 4.15.0-29-generic
GCC version 5.4.0
