### ISSUE TITLE
Immediate sign extension in a unsigned instruction

### ISSUE THREAD

**Issue by Fabio752** [m8pple/arch2-2018-cw#37]
Is the immediate always signed extended or it depends on if the instruction is either signed or unsigned?
I mean, in the following example ( $1 initial value equal 0):
ADDIU $1, $1, 0xFFFF

- is the 0xFFFF firstly sign extended in 0xFFFFFFFF and then interpreted as unsigned in the result
- or the sign extension takes into account that the instruction is unsigned so it results in 0x0000FFFF

**Comment by jjd06** [comment]
Immediates are not always sign extended, but whether or not they are doesn't depend on whether or not the instruction is a signed or unsigned variant. The immediate behaviour for each instruction is detailed on the reference data card at the front of the textbook.
