### ISSUE TITLE
consecutive delayed branch

### ISSUE THREAD

**Issue by BenShen98** [m8pple/arch2-2018-cw#38]
I had written an assembly code to test for the case with branch next to each other, with the code shown below:
> add $1,$2,$3
jr $5 //CALL it A
j 4 // CALL it B
jr $0
jr $0

I thought it will cause "A" get delayed, cause undefined behaviour as when "A" branch happens and "B" branch is get delayed.

But the mips code actually is: 
>10000000:	00a00008 	jr	a1
10000004:	00430820 	add	at,v0,v1
10000008:	10000001 	b	0x10000010
1000000c:	00000000 	nop
10000010:	00000008 	jr	zero
10000014:	00000000 	nop
10000018:	00000008 	jr	zero
1000001c:	00000000 	nop

With nop as pipeline stall, preventing this behaviour happing.

As the result, I would like to check 
- [ ] our simulator DOES NOT need have defined behaviour OR exception if 2 branches are consecutive.
- [ ] In general, if the instruction binary will not be produced by a compiler, no defined behaviour OR exception is required

**Comment by jjd06** [comment]
It is not legal to put a branch in a delay slot, hence why the assembler is adding NOPs. How you choose to respond to such undefined instruction sequences is up to you. See also #27 and #15.
