### ISSUE TITLE
Testbench timeout

### ISSUE THREAD

**Issue by olly-larkin** [m8pple/arch2-2018-cw#39]
Is there an estimated timeout for the testbench at the moment or will it be decided after submission?

Asking because currently our testbench takes a couple minutes at most and we were wondering if it will need streamlining or trimming down a bit.

**Comment by jjd06** [comment]
That's fine. I don't anticipate needing to time out on testbench runs, just individual simulator runs. If a single test takes an unreasonable time (on the order of seconds) to run, that will be an issue.
