### ISSUE TITLE
Memory-Map too big

### ISSUE THREAD

**Issue by alexander3605** [m8pple/arch2-2018-cw#4]
The space needed for the Memory-map defined in the specifications has a maximum offset of 0xFFFFFFFF (roughly 4 GB of memory). If we try to recreate it with a single array we get an error from the compiler saying that its size is too big. 
Do we need to preallocate all the space at the beginning (with one or more arrays) or allocate memory dynamically (using data structures such as linked lists storing both simulation address and data), thereby increasing maximum memory needed by a factor of 2?

**Comment by m8pple** [comment]
Good question, and this comes back to the architectural aspects
of things (and part of the reason for choosing memory mapping).

I used to have a 80386 machine, which was technically a 32-bit
machine. At the time it had 4MB of memory (which was considered
a fair amount), and the cost of giving it 4GB of memory would have
been ~£250000 (in 1994 money), ignoring that no motherboard could
support it.

Similarly, there exist x86_64 emulators, which can run 64-bit
processs, but would technically require the simulator to allocate
exa-bytes of memory.

So in both the hardware and emulation cases, it is almost never
the case that you can fill your address space with RAM.

The two approaches you suggest both make sense. If you were
simulating a dynamic environment, where you didn't know how
much memory was going to be used, then something dynamic would
make sense.

In this case, you have an extremely static setup, so the approach
of pre-allocating everything at the start is probably the best approach.

If you think about all the machine state:
- CPU : registers
- memory : ROM + RAM

We know this is never going to change, so you might as well decided
how you are going to store it, and allocate it all up front.

(There will be other state in your Simulator, but that is the important
Program visible stuff).

David Thomas
