### ISSUE TITLE
Register change during load delay

### ISSUE THREAD

**Issue by olly-larkin** [m8pple/arch2-2018-cw#41]
In the load delay slot, the instruction will execute before the register has been written to in the load, but if the delay slot instruction also changes the value of said register, does this happen before or after the load writes to the register, or is it undefined?

For example:

addiu $4, $0, 10
sw $4, 0($5)
lw $2, 0($5)
addiu $2, $0, 5

Would the value of register 2 be 10 or 5 after execution? Or just undefined? (assuming that $5 points to valid data memory).

**Comment by jjd06** [comment]
As per the reasoning given for other delay slot subtleties (see e.g. #38 re consecutive branches), this is implementation defined, so it is up to you how you choose to behave.
