### ISSUE TITLE
Load delay slot

### ISSUE THREAD

**Issue by ES5017** [m8pple/arch2-2018-cw#44]
There isn't a single mention of 'load delay' in the textbook or in MIPS32™ Architecture For Programmers Volume II: The MIPS32™ Instruction Set. The only information I can find about it is a short paragraph on wikepedia, and some random university mips pages.

I'd like to know if this concept needs to be implemented. Do we need to keeep the old values of the registers for one cycle, then after that make the new values available? Or do we need to check if an instruction in the load delay slot accessing a register that is still being loaded in should cause an exception? Or is this something we don't need to worry about as it is invalid mips code?

**Comment by BenShen98** [comment]
You may find [this information](https://github.com/m8pple/arch2-2018-cw/files/2568643/mips-iv.pdf)useful, I found it in the previous issue #6.

From what I understand, if the documentation says it was undefined, then you don't need to implement anything for the undefined behaviour. As you just can't write a test case to test what is not defined.

**Comment by jjd06** [comment]
@Ben20082010 is correct regarding undefined behaviour: you are free to do whatever makes things easiest/most convenient for you.
