### ISSUE TITLE
Address Alignment Check

### ISSUE THREAD

**Issue by liqinyang** [m8pple/arch2-2018-cw#45]
In the reference book _MIPS IV Instruction Set Revision 3.2 By Charles Price_,
The memory related instructions have restrictions, (eg.SH)

> The effective address must be naturally aligned. If the least-significant bit of the address is non-zero, an Address Error exception occurs.
MIPS IV: The low-order bit of the offset field must be zero. If it is not, the result of the instruction is undefined.

As we are implementing MIPS I, can an effective address be made from both odd base and offset?

For example, if I have 0x20000007 in the base register and 0x0001 in the offset to make the effective address 0x20000008 which is aligned, will this instruction cause an address exception?

**Comment by jjd06** [comment]
I believe that your interpretation is correct. It appears that the additional restriction on offsets is MIPS-4-specific, so, for MIPS-1, only effective address alignment matters. Even for MIPS-4, however, the behaviour can be implementation defined.
