### ISSUE TITLE
full instruction memory

### ISSUE THREAD

**Issue by MarcoSelvatici** [m8pple/arch2-2018-cw#49]
In case there are too many instructions loaded in the simulator (i.e. more than enough to fill up all the instructions memory), how should the simulator behave? Should it throw a memory exception, an internal error, just crash, or something else?

**Comment by jjd06** [comment]
Within reason, how you choose to handle this is up to you. Given that you have a fixed-sized instruction memory (which you must not violate), the most natural thing to do seems to be to just stop writing once you run out of space to write to. If you do this, unless the final instruction happens to be `jr $0` (or equivalent), your simulator will ultimately throw an exception when it runs out of instruction memory to read from.
