### ISSUE TITLE
Naming instruction under test when multiple tests for same instruction

### ISSUE THREAD

**Issue by JordanGlanfield** [m8pple/arch2-2018-cw#53]
In the specification for the test bench it says that the 2nd field in the CSV output should be the instruction under test. If we have multiple tests for the same instruction, what naming convention should we use?

For example, for add, should we use ADD, ADD for both and change the test ID? Or could we use ADD and ADD-overflow?

Also, can we use lower case for the instruction name instead.

**Comment by jjd06** [comment]
It should be the same of the *primary* instruction under test. For your example, you should use "ADD" for both.

**Comment by JordanGlanfield** [comment]
Thank you
