### ISSUE TITLE
Malformed instructions

### ISSUE THREAD

**Issue by adamurban98** [m8pple/arch2-2018-cw#55]
Dear Dr @jjd06 . Following our conversation I would like to ask you for a definite resolution whether we can treat **instructions with unused field _not_ set to 0** as undefined behaviour. E.g. the `shamt` field in ADD.

**Comment by jjd06** [comment]
This is dictated by the ISA. If the ISA says that field x must be y for instruction z, then x != y for z should cause an instruction exception. Equally, if the ISA says that field x is "don't care" for instruction z, then x should be ignored when z is executed. There are relatively few things that are not explicit in the ISA; only for these can you implement arbitrary behaviour.
