### ISSUE TITLE
Test bench timeouts

### ISSUE THREAD

**Issue by SCFXTRADING** [m8pple/arch2-2018-cw#56]
Should our test bench have timeouts? Will you run our test bench on a simulator that for example has a bug causing an infinite loop in the code? Also how much time does our test bench get to run?

**Comment by jjd06** [comment]
I assume that you're thinking of things like e.g. (ignore delay slots)

```
	li $t0, 10
loop:	addi $t0, $t0, -1
	beq $t0, $zero, exit
	j loop
exit:	
```

with a broken `beq` rather than buggy simulator implementations with infinite loops within them. If so, sure; why shouldn't I test this? :)

See #39 re testbench runtime.
