### ISSUE TITLE
Earliest hash or latest hash

### ISSUE THREAD

**Issue by SCFXTRADING** [m8pple/arch2-2018-cw#57]
> For groups that submit no hashes, the latest version of your code will be pulled and tested instead. For groups that submit two hashes, the earliest hash submitted (in commit history terms) will be us

The earliest hash? Is it supposed to say the latest hash?

**Comment by jjd06** [comment]
No.

**Comment by SCFXTRADING** [comment]
But if a group doesn't submit you use the latest hash? So there is no benefit for a group to submit a hash, it is better to leave the box blank so that you take the latest commit?

**Comment by Darrekt** [comment]
My partner and I submitted yesterday, but have resubmitted today. Both of the submissions have consistent hashes between the both of us and it would be unfair in my opinion to take the earlier submission. To clear up confusion, do you perhaps mean to say:

* IF two members submit differing hashes, the earlier between the two of them will be taken.
* If two members submit consistent hashes, between multiple submissions, the latest submission will be taken at that hash.

**Comment by jjd06** [comment]
If a group doesn't submit any hashes, their marks are capped at 20%: the maximum available for the reflective statement. If their (latest) submissions contain differing hashes, I will use the earlier one.

Multiple submissions are fine; the latest one automatically replaces all earlier ones.

**Comment by SCFXTRADING** [comment]
Ok thanks for the clarification
