### ISSUE TITLE
MIPS Reference Sheet

### ISSUE THREAD

**Issue by twutang** [m8pple/arch2-2018-cw#6]
Is this a reasonable and accurate source for the instruction opcodes? 

http://www2.engr.arizona.edu/~ece369/Resources/spim/MIPSReference.pdf

**Comment by m8pple** [comment]
It's a good overview, but by trying to be a brief guide it is going to miss some details.
So reasonable, yes; accurate, probably not in some cases.

So you can use it as a general guide, but occasionally you might need to dive
into the details with the full MIPS ISA. For example:

 https://www.cs.cornell.edu/courses/cs3410/2008fa/MIPS_Vol2.pdf

or 

http://math-atlas.sourceforge.net/devel/assembly/mips-iv.pdf

(Note that the MIPS-IV version includes ISA extensions, but also includes
the core MIPS1).
