### ISSUE TITLE
edits on linker.ld 

### ISSUE THREAD

**Issue by wmvndrscht** [m8pple/arch2-2018-cw#8]
I noticed that the linker.ld provided seems to include the values for the size of the section (text and data) rather than the offset when compared with memory map provided?

I thought the linker script is supposed to define the offset not size?

**Comment by m8pple** [comment]
Ah, yes - you're completely right. The `.data` section is at the wrong position.

I must have copied in the wrong version, and not noticed because I didn't
happen to use any variables.

Thanks, I'll update the example linker script.
