### ISSUE TITLE
Reading from Executable Memeory

### ISSUE THREAD

**Issue by VasiliosRallis** [m8pple/arch2-2018-cw#9]
According to the Memory Map Diagram, the simulator has read access to the Executable Memory. Does this mean that a lw instruction could theoretically load a word from the Executable Memory into a register?

This doesn't seem to follow the way we have been designing the processor in the lectures.

**Comment by m8pple** [comment]
Yes, the Binary could read from instruction memory. As you point out, this differs from
the current abstract block design we have, where we have completely separate instruction
and data memories (i.e. [a Harvard machine](https://en.wikipedia.org/wiki/Harvard_architecture),
which allows us to do two reads or one read + one write in one cycle.

In some low-level embedded-oriented CPUs this restriction is actually physical - there is
one data-path to the instruction ROM, and it never touches the main data-path. There
are cost and speed advantages there, as well as some additional security.

However, in more general processors like MIPS those blocks still have a view onto a
single logical unified address space, and are actually most likely caches backed by one
set of physical memories and devices. So if you try to load a word from the instruction
memory, it will be fetched into the data cache, while if you try to execute that instruction
it will be loaded into the instruction cache. This is also how an OS loads programs into
memory, by using loads and stores to put the instructions into RAM, then when execution
starts they are available for use by the instruction cache (with some low-level flushing
of caches, to make sure they are synchronised).

Related: one thing I haven't given you is the ability to load a data segment, so you don't
have a way of creating variables initialised to a particular value. But as you point out,
you _can_ do a `lw` from instruction memory, and that can contain whatever you want...
